### ISSUE TITLE
What is the rationale behind linked trips / blocks?

### ISSUE THREAD

**Issue by lukstafi** [line72/subte#3]
Hi!

Just to let you know, I'm working on my fork of *subte* at https://github.com/lukstafi/subte . Feel free to review and pull commits you find useful. I'll be adding more features but I only have a week left to work on it.

What is the use case / meaning / rationale of the linked trips feature? There does not seem to be such a thing in GTFS.

**Comment by line72** [comment]
First, Thanks for taking up and working on this project, it needs lots of love!

As for the linked trips, this can actually be very important. Many transit agencies do something called interlining. This is when one bus, say the #1, finishes its route, and then continues on as a different route, say the #5. This causes a problem in trip planning, since the underlying algorithm doesn't know that there is any relationship between the #1 and the #5.

So for example, if you as a rider were taking the #1 into town, and were then going to continue on to the #5, the algorithm would tell you to get off the bus as the final stop of the #1 and then board the #5 bus. In this case, it is the same bus, so there is no need to get off and get back on. But worse than that, most trip planning algorithms like to make sure there is enough time for a transfer, and again, since it doesn't know it's the same bus, it may tell you to get off the #1, then wait 15 minutes for the next #5.

The linked trips allows you to tell the system that at the end of this trip, this bus will then turn into this next trip. The GTFS specification defines this in the block_id of each trip. Using the same block_id for multiple trips means it is the same vehicle taken them.

https://developers.google.com/transit/gtfs/reference#trips_fields

**Comment by lukstafi** [comment]
Thanks! I've been reading this reference document but somehow missed the description.

I've implemented the features I've been interested in. I'll add a crude localization (dictionary) to (English and) Polish.
